stages:
  - build
  - test
  - deploy

default:
  image: phpdockerio/php80-cli

install-deps:
  stage: build
  script:
    - composer install
  artifacts:
    expire_in: 3 hours
    untracked: true
    paths:
      - bin/**
      - config/**
      - public/**
      - src/**
      - vendor/**
      - .env
      - .php_cs.dist
      - composer.json
      - composer.lock
      - symfony.lock

test-php-cs-fixer:
  stage: test
  dependencies:
    - install-deps
  script:
    - vendor/bin/php-cs-fixer fix --verbose --diff --dry-run

test-phpunit:
  stage: test
  dependencies:
    - install-deps
  script:
    - ./bin/phpunit

.deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."