stages:
  - build
  - test
  - prepare
  - deploy

default:
  image: jellybellydev/ci-cd-theory-into-practice:latest

install-deps:
  stage: build
  script:
    - composer install
  artifacts:
    expire_in: 3 hours
    untracked: true
    paths:
      - bin/**
      - config/**
      - public/**
      - src/**
      - vendor/**
      - .env
      - .php_cs.dist
      - composer.json
      - composer.lock
      - symfony.lock

php-cs-fixer:
  stage: test
  dependencies:
    - install-deps
  script:
    - vendor/bin/php-cs-fixer fix --verbose --diff --dry-run

lint-yaml-config:
  stage: test
  dependencies:
    - install-deps
  script:
    - bin/console lint:yaml config

phpunit:
  stage: test
  dependencies:
    - install-deps
  script:
    - bin/phpunit

phpunit-coverage:
  stage: test
  dependencies:
    - install-deps
  script:
    - XDEBUG_MODE=coverage bin/phpunit --colors=never --coverage-text


.prepare_template: &prepare_template
  script:
    - composer install --no-dev --optimize-autoloader
    - composer dump-autoload --no-dev --classmap-authoritative
    - composer dump-env
  artifacts:
    expire_in: 3 hours
    untracked: true
    paths:
      - bin/**
      - config/**
      - public/**
      - src/**
      - vendor/**
      - .env
      - .env.local
      - .env.local.php
      - composer.json

prepare:staging:
  stage: prepare
  <<: *prepare_template
  before_script:
    - echo "APP_ENV=staging" >> .env.local
  only:
    - master

prepare:prod:
  stage: prepare
  <<: *prepare_template
  before_script:
    - echo "APP_ENV=prod" >> .env.local
  only:
    - tags

.deploy_template: &deploy_template
  image: spy86/ansible:latest
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
#    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
#    - eval $(ssh-agent -s)
#    - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - echo "$DEPLOY_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - ssh-keyscan -H $HOST_FOR_SSH_KEYSCAN >> ~/.ssh/known_hosts
    - if [[ -f gitlab_variables ]]; then source gitlab_variables; fi
    - cd ansible-deploy
    - 'echo "gitlab_access_token: \"${GITLAB_ACCESS_TOKEN_API}\"" > user-vars.yml'
    - 'echo "ssh_private_key_file: \"~/.ssh/id_rsa\"" >> user-vars.yml'

deploy:staging:
  stage: deploy
  variables:
    HOST_FOR_SSH_KEYSCAN: "161.97.172.133"
    DEPLOY_PRIVATE_KEY: $MY_DEPLOY_PRIVATE_KEY
  <<: *deploy_template
  dependencies:
    - prepare:staging
  script:
    - echo "Deploy $CI_COMMIT_REF_NAME to staging server"
#    - ansible-playbook deploy.yml -i inventories/staging -e "app_version=$CI_COMMIT_REF_NAME ci_job_id=$CI_JOB_ID_ARTIFACTS"
    - ansible-playbook deploy.yml -i inventories/staging -e "app_version=$CI_COMMIT_REF_NAME"
  only:
    - master
