stages:
  - build
  - test
  - prepare
  - deploy

default:
  image: jellybellydev/ci-cd-theory-into-practice:latest

install-deps:
  stage: build
  script:
    - composer install
  artifacts:
    expire_in: 3 hours
    untracked: true
    paths:
      - bin/**
      - config/**
      - public/**
      - src/**
      - vendor/**
      - .env
      - .php_cs.dist
      - composer.json
      - composer.lock
      - symfony.lock

php-cs-fixer:
  stage: test
  dependencies:
    - install-deps
  script:
    - vendor/bin/php-cs-fixer fix --verbose --diff --dry-run

lint-yaml-config:
  stage: test
  dependencies:
    - install-deps
  script:
    - bin/console lint:yaml config

phpunit:
  stage: test
  dependencies:
    - install-deps
  script:
    - bin/phpunit

phpunit-coverage:
  stage: test
  dependencies:
    - install-deps
  script:
    - XDEBUG_MODE=coverage bin/phpunit --colors=never --coverage-text


.prepare_template: &prepare_template
  script:
    - composer install --no-dev --optimize-autoloader
    - composer dump-autoload --no-dev --classmap-authoritative
    - composer dump-env
  artifacts:
    expire_in: 3 hours
    untracked: true
    paths:
      - bin/**
      - config/**
      - public/**
      - src/**
      - vendor/**
      - .env
      - .env.local
      - .env.local.php
      - composer.json

prepare:staging:
  stage: prepare
  <<: *prepare_template
  before_script:
    - echo "APP_ENV=staging" >> .env.local
  only:
    - master

prepare:prod:
  stage: prepare
  <<: *prepare_template
  before_script:
    - echo "APP_ENV=prod" >> .env.local
  only:
    - tags

.deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."