# file: staging hosts
all:
  vars:
    ansible_user: "jellybellydev"
    job_env: "staging"
    home_path: "/home/jellybellydev/staging-cicd"
    current_path: "{{ home_path }}/current"
    current_prev_path: "{{ current_path }}_prev"
    check_host: "staging-cicd.jellybellydev.it"

  hosts:
    161.97.172.133:
