# file: production hosts
all:
  vars:
    ansible_user: "jellybellydev"
    ansible_ssh_private_key_file: "{{ ssh_private_key_file }}"
    app_env: "prod"
    home_path: "/home/jellybellydev/cicd"
    current_path: "{{ home_path }}/current"
    current_prev_path: "{{ current_path }}_prev"
    check_host: "cicd.jellybellydev.it"

  hosts:
    161.97.172.133:
